/** Common HTTP headers for dropdown suggestions (Postman-style) */
export const COMMON_HEADERS: string[] = [
  "Accept",
  "Accept-Charset",
  "Accept-Encoding",
  "Accept-Language",
  "Authorization",
  "Cache-Control",
  "Content-Type",
  "Cookie",
  "Origin",
  "User-Agent",
  "X-Requested-With",
  "X-API-Key",
  "X-Auth-Token",
  "X-CSRF-Token",
  "Content-Length",
  "Content-Encoding",
  "Content-Disposition",
  "Connection",
  "Host",
  "Referer",
  "Referrer-Policy",
  "If-Match",
  "If-None-Match",
  "If-Modified-Since",
  "ETag",
  "Expect",
  "Forwarded",
  "Sec-Fetch-Dest",
  "Sec-Fetch-Mode",
  "Sec-Fetch-Site",
  "Upgrade-Insecure-Requests",
];

export type BodyType = "none" | "text" | "json";
